---
# Playbook cho tất cả các host
- hosts: all
  tasks:
    - name: Make folder 
      file:
        path: /home/isofh/demo
        state: directory
        # owner: isofh
        # group: isofh
        mode: "0755"
    - name: Copy shell check server to Project
      copy:
        src: /home/isofh/ansible/hihi.txt
        dest: /home/isofh/demo/hihi.txt
        # owner: isofh
        # group: isofh
        mode: "0644"
