---
# Playbook cho tất cả các host
- hosts: all
  tasks:
    # Tạo thư mục
    - name: Make folder 
      file:
        path: /home/ubuntu/demo
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    # Copy file từ server ansible vào thư mục vừa tạo
    - name: Copy shell check server to Project
      copy:
        src: /home/isofh/ansible/hihi.txt
        dest: /home/ubuntu/demo/hihi.txt
        owner: ubuntu
        group: ubuntu
        mode: "0644"
